### ISSUE TITLE
release rebuild

### ISSUE THREAD

**Issue by pums974** [frace/kodi-overlay#14]
It would be nice to have an ebuild for the released version.

**Comment by frace** [comment]
Fixed with https://github.com/frace/kodi-overlay/pull/15

**Comment by anthonyryan1** [comment]
@pums974 Now that the official ebuild in the portage tree is up to date, do you still intend to use the stable ebuild in this overlay?

**Comment by pums974** [comment]
No thank you.
And thank you very much for the ebuild.

2015-02-21 19:21 GMT+01:00 Anthony Ryan <notifications@github.com>:
