### ISSUE TITLE
media-tv/kodi: Possibly merge overlay efforts

### ISSUE THREAD

**Issue by maggu2810** [frace/kodi-overlay#19]
Hello,
there exists another kodi ebuild in another overlay (https://github.com/MathyV/gentoo-overlays-media/issues/1). Perhaps we could merge our efforts.
Please have a look at: MathyV/gentoo-overlays-media#1

**Comment by frace** [comment]
Sorry I lost sight of that point in your last report. I'll join the discussion at the weekend.

**Comment by frace** [comment]
Left a message on MathyV/gentoo-overlays-media#1

**Comment by frace** [comment]
Reopened in order to have a visible reminder.

**Comment by frace** [comment]
Closing since I received no response.

**Comment by maggu2810** [comment]
Too bad that @MathyV has not leave a message.
Thank you for your efforts.

**Comment by frace** [comment]
@maggu2810 After having a closer look at the overlay recently, I felt that the goals of both overlays are too different to get merged anyway.

**Comment by MathyV** [comment]
Sorry about that, I didn't get a notification about your comment after I closed the issue (or I missed it). In any case, yes, the goal of my repository is for ebuilds I created once for a quick update or ones that aren't in portage anymore that I still use. At the moment the kodi ebuild is not even there anymore as it is now in the official tree.

I do however still have the kodi-addon-pvr ebuild that you don't seem to have and also isn't in the official tree. If you want I can create a pull request for that.

**Comment by maggu2810** [comment]
For pvr this one could be related: https://bugs.gentoo.org/show_bug.cgi?id=555792
See #27

**Comment by frace** [comment]
@MathyV No problem. :)
In regards to the kodi-addon-pvr ebuild - I'm pretty sure that is obsolete since team KODI overhauled the addon system. For details see: https://bugs.gentoo.org/show_bug.cgi?id=555792

**Comment by MathyV** [comment]
Ah, it's about time they did that :-) Looking forward to seeing the 15.1 ebuild then :-)
