### ISSUE TITLE
kodi-14.0 doesn't require xdpyinfo

### ISSUE THREAD

**Issue by ostash** [frace/kodi-overlay#22]
There is no references to it sources tarball.

**Comment by frace** [comment]
It's neede in FEH.py

https://github.com/xbmc/xbmc/blob/fc646f39437614e30333b80e32a69a957a375e89/tools/Linux/FEH.py.in

**Comment by ostash** [comment]
Sorry. My fault.

**Comment by frace** [comment]
Np :)
