### ISSUE TITLE
media-tv/kodi: Version bump to stable version 14.1

### ISSUE THREAD

**Issue by vitalogy** [frace/kodi-overlay#24]
have look at http://kodi.tv/download/
thx for this overlay

**Comment by frace** [comment]
@vitalogy Thanks for the report! If you like it you are welcome to star this repo. :)
The KODI source is not on the mirrors yet: http://mirrors.kodi.tv/releases/source/

**Comment by frace** [comment]
Fixed with https://github.com/frace/kodi-overlay/commit/4c6cb050a8887bd2413116fb3a2bdfc2a0d52f5b
