### ISSUE TITLE
media-tv/kodi: missing pvr addon

### ISSUE THREAD

**Issue by jonashrem** [frace/kodi-overlay#26]
Sorry to open onther ticket

I finally magaged to get kodi installed. I merged 13.1 with pvr use flag (X alsa avahi bluray caps css fishbmc java joystick midi mysql nfs opengl projectm pulseaudio pvr rsxs rtmp samba sdl sftp sse sse2 udisks upnp upower usb vaapi vdpau xrandr) and it works fine, but I can't enable live tv.

**Comment by frace** [comment]
No worries!

Do you talk about xbmc-13.1?

**Comment by jonashrem** [comment]
oh no. I meant 14.1 of course. Sorry

**Comment by frace** [comment]
Ok, I think we are missing an ebuild here. :) That didn't stand out until now since I don't use the pvr features personally.

If I find time during the weekend I'll add an ebuild. If it is urgent you are welcome to open a pull request.

**Comment by jonashrem** [comment]
No, not urgent ;). Take you time.

**Comment by frace** [comment]
I created a pull request https://github.com/opdenkamp/xbmc-pvr-addons/pull/426
This would make it more suitable for an ebuild and Gentoo Linux.

**Comment by frace** [comment]
Fixed with https://github.com/frace/kodi-overlay/commit/c7d0b1d84c364f0007c3cc3c76c440f0c7a5d4b3
