### ISSUE TITLE
kodi fail build in in working directory of JsonSchemaBuilder/native

### ISSUE THREAD

**Issue by mimir1980** [frace/kodi-overlay#28]
cd native; ./configure --prefix=/var/tmp/portage/media-tv/kodi-14.1/work/xbmc-14.1-Helix/tools/depends/native/JsonSchemaBuilder
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
make -C native
make[2]: Entering directory `/var/tmp/portage/media-tv/kodi-14.1/work/xbmc-14.1-Helix/tools/depends/native/JsonSchemaBuilder/native'
g++ -DPACKAGE_NAME=\"JsonSchemaBuilder\" -DPACKAGE_TARNAME=\"jsonschemabuilder\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"JsonSchemaBuilder\ 1.0\" -DPACKAGE_BUGREPORT=\"me@mail.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"jsonschemabuilder\" -DVERSION=\"1.0\" -I.     -march=bdver2 -O2 -pipe -MT JsonSchemaBuilder.o -MD -MP -MF .deps/JsonSchemaBuilder.Tpo -c -o JsonSchemaBuilder.o JsonSchemaBuilder.cpp
mv -f .deps/JsonSchemaBuilder.Tpo .deps/JsonSchemaBuilder.Po
g++  -march=bdver2 -O2 -pipe  -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -o JsonSchemaBuilder JsonSchemaBuilder.o  
make[2]: Leaving directory `/var/tmp/portage/media-tv/kodi-14.1/work/xbmc-14.1-Helix/tools/depends/native/JsonSchemaBuilder/native'
make -C native install
make[2]: Entering directory `/var/tmp/portage/media-tv/kodi-14.1/work/xbmc-14.1-Helix/tools/depends/native/JsonSchemaBuilder/native'
make[3]: Entering directory `/var/tmp/portage/media-tv/kodi-14.1/work/xbmc-14.1-Helix/tools/depends/native/JsonSchemaBuilder/native'
 /bin/mkdir -p '/var/tmp/portage/media-tv/kodi-14.1/work/xbmc-14.1-Helix/tools/depends/native/JsonSchemaBuilder/bin'
  /usr/bin/install -c JsonSchemaBuilder '/var/tmp/portage/media-tv/kodi-14.1/work/xbmc-14.1-Helix/tools/depends/native/JsonSchemaBuilder/bin'
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/var/tmp/portage/media-tv/kodi-14.1/work/xbmc-14.1-Helix/tools/depends/native/JsonSchemaBuilder/native'
make[2]: Leaving directory `/var/tmp/portage/media-tv/kodi-14.1/work/xbmc-14.1-Helix/tools/depends/native/JsonSchemaBuilder/native'
touch .installed-native
make[1]: Leaving directory `/var/tmp/portage/media-tv/kodi-14.1/work/xbmc-14.1-Helix/tools/depends/native/JsonSchemaBuilder'
 * ERROR: media-tv/kodi-14.1 failed (prepare phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=media-tv/kodi-14.1'`,
 * the complete build log and the output of `emerge -pqv '=media-tv/kodi-14.1'`.
 * This ebuild is from an overlay named 'kodi-overlay': '/usr/local/portage/kodi-overlay/'
 * The complete build log is located at '/var/tmp/portage/media-tv/kodi-14.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-tv/kodi-14.1/temp/environment'.
 * Working directory: '/var/tmp/portage/media-tv/kodi-14.1/work/xbmc-14.1-Helix'
 * S: '/var/tmp/portage/media-tv/kodi-14.1/work/xbmc-14.1-Helix'

**Comment by frace** [comment]
Closing, need info.
