### ISSUE TITLE
Update for network-sandbox

### ISSUE THREAD

**Issue by anthonyryan1** [frace/kodi-overlay#29]
Please tag this as a todo and assign it to me, I'm creating it so it's documented and I can work on this for a future release.

Installing kodi with `FEATURES="network-sandbox"` fails because the build process fetches the kodi-specific copy of ffmpeg from https://github.com/xbmc/FFmpeg/releases. We should be handling that in SRC_URI / EGIT_REPO_URI.

**Comment by frace** [comment]
Tagged. Unfortunately it seems like I can't assign an issue to anyone else but me. However it's documented by the git log anyways, isn't it?

**Comment by anthonyryan1** [comment]
Thanks, I won't worry about assigning it then. I just wanted to make my intention to address this issue clear.

**Comment by frace** [comment]
@anthonyryan1 Is this still an issue?

**Comment by anthonyryan1** [comment]
I haven't checked lately, but if we're not fetching the static ffmpeg in SRC_URI it still will need work. I'll schedule some time to resolve this in the next few days.

**Comment by frace** [comment]
No hurry :)

**Comment by anthonyryan1** [comment]
I've run into a bit of a roadblock executing this.

In order to resolve this issue, we need to fetch ffmpeg before we start compiling, rather than after we're already at it. Normally this would just be an extra `SRC_URI` but after adding it to that it seems to be ignored in the live ebuild which is the only one currently included in this overlay.

While I can make this work for stable versions, the changes necessary to make it work in the live ebuild are eluding me. So since I'm not able to do anything I'm going to close this until I revisit it someday or someone with the ability to see what I'm overlooking is able to work on it.

For reference, at this time the best place to get the Kodi specific ffmpeg version seems to be:
```
https://github.com/xbmc/FFmpeg/archive/${FFMPEG_VERSION}-${CODENAME}.tar.gz ${P}-ffmpeg-${FFMPEG_VERSION}.tar.gz
```
