### ISSUE TITLE
Help needed: Clone from <05.18.2016 wanted

### ISSUE THREAD

**Issue by frace** [frace/kodi-overlay#31]
Well yeah, I messed up history. would be nice if someone could tell me if she/he has a clone from before 05.18.2016.

@maggu2810 @anthonyryan1 does any of you both have a recent clone by accident? :)

Thanks a lot!

**Comment by maggu2810** [comment]
My Github fork is from "Jan 12, 2015", so rather old.
Need to check at home if one of my machine still syncs this overlay.
But I have to admit I stopped using Kodi, so I assume I cannot help.

**Comment by maggu2810** [comment]
If you "know" a commit ID, then perhaps we can still fetch the unreferenced ID

**Comment by maggu2810** [comment]
https://github.com/frace/kodi-overlay/tree/b0bd8d7/

**Comment by maggu2810** [comment]
https://github.com/frace/kodi-overlay/tree/65b9bb477ac63e12b21b0ea4ba80a9e5be94c989

**Comment by maggu2810** [comment]
If you see the Github page with the respective commit ID (see examples above), you (with write permissions) should be able to click on the "Tree: ..." drop down list (where you normally select a branch or a tag) and add a branch name to the text box.
After that a new branch that refers to that commit ID has been created.
You can checkout this branch, and use the command line tool (rebase, ...) to push a recent master.

**Comment by frace** [comment]
Thanks a lot for your help. I found the most recent hash in my bash history: https://github.com/frace/kodi-overlay/commits/b0bd8d71b9e37764a6ee9a299f304f98d1c285d8

Btw. do I know you from gentoo-forum.de?

**Comment by maggu2810** [comment]
Perhaps, but my last activity (I looked at the page) has been at "20.09.2012, 23:33".
So long time ago...

**Comment by frace** [comment]
Thanks for your help again! All fixed now.
Haven't been active on that forum for a long time either. ^^
