### ISSUE TITLE
Not building on supermicro server

### ISSUE THREAD

**Issue by kbaegis** [frace/kodi-overlay#32]
Hi there,

New using Kodi.  This overlay does not build at all (even with all options turned off) on my Supermicro D525 server. 

emerge info: http://pastebin.com/8naETvQH
emerge pqv: [ebuild  N    ] media-tv/kodi-16.0  USE="opengl -X -airplay -alsa -avahi -bluetooth -bluray -caps -cec -css -dbus -debug -gles -java -joystick -midi -mysql -nfs (-profile) -pulseaudio -rtmp -samba -sftp {-test} -texturepacker -udisks -upnp -upower -usb -vaapi -vdpau -webserver" PYTHON_TARGETS="-python2_7"
build log: http://pastebin.com/2eJ1A6RR

**Comment by frace** [comment]
This issue is obsolete since Gentoo upstream provides revised ebuilds.
